apps/diets/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('apps.diets.views',
    url(r'^diet/$', 'get_diet_today', name='diet_today'),
)

apps/exercises/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('apps.exercises.views',
    url(r'^exercises/(?P<trainer_id>[\w]+)/$', 'trainer_exercises', name='exercises'),
)

apps/progress/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('apps.progress.views',
    url(r'^api/trainer/$', 'get_trainer', name='trainer'),
    url(r'^api/trainers/$', 'get_trainers', name='trainers'),
    url(r'^api/trainer/exercises/$', 'get_trainer_exercises', name='trainer_exercises'),
    url(r'^api/online/set/$', 'set_time_online', name='time_online'),
    url(r'^api/video/viewed/$', 'video_viewed', name='video_viewed'),
    url(r'^api/diet/viewed/$', 'diet_viewed', name='diet_viewed'),
    url(r'^api/burned/$', 'get_burned_calories', name='burned_calories'),
    url(r'^api/share/$', 'share_result', name='share_result'),
    url(r'^progress/exercise/(?P<exercise_id>[\w]+)/$', 'progress_exercise', name='progress_exercise'),
)

project/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.shortcuts import render


urlpatterns = patterns('',
    url(r'^$', 'apps.exercises.views.home', name='home'),

    url(r'^', include('apps.accounts.urls', namespace='accounts')),
    url(r'^', include('apps.exercises.urls', namespace='exercises')),
    url(r'^', include('apps.diets.urls', namespace='diets')),
    url(r'^', include('apps.progress.urls', namespace='progress')),
    url(r'', include('social.apps.django_app.urls', namespace='social')),

    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^html/(?P<template_name>.*\.html)$', (lambda request, template_name: render(request, template_name))),
    )

templates/base.html
{% load pipeline  %}<!DOCTYPE html>
<html lang="ru">
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<title>Фото истории</title>
	<meta name="keywords" content="{FIXME}">
	<meta name="description" content="{FIXME}">
	<meta name="viewport" content="width=device-width">
	<link href="html/favicon.ico" rel="icon" type="image/x-icon" />
	<link href="html/favicon.ico" rel="shortcut icon" type="image/x-icon" />
	<link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700,400italic&subset=latin,cyrillic' rel='stylesheet' type='text/css'>

	</head>
	<body>
		<div>
		{% include 'blocks/messages.html' %}
		{% block content %}
		{% endblock %}
		</div>
	</body>
</html>

templates/blank.html
{% extends 'base.html' %}

{% block content %}

    {% include 'blocks/header.html' %}
    {% if user.username %}
        пустая страница
        {{ diets }}
    {% endif%}

{% endblock %}

templates/exercises.html
{% extends 'base.html' %}

{% block content %}

    {% include 'blocks/header.html' %}
    {% if user.username %}
        Упражнения тренера <strong>{{ trainer.family_name }}, {{ trainer.name }}</strong>. День <strong>{{ day }}</strong><br />
        {% if exercises %}
            {% for exercise in exercises %}
                {{ exercise.title }}. Ссылка на видео <a href="{{ exercise.video_url }}">ссылка</a>. Рекомендовано: подходов {{ exercise.prescription_sets }}, повторений в подходе {{ exercise.prescription_repetitions }}. Выполняя рекомендации вы будете сжигать {{ exercise.repetition_calories_burned }} калорий за повтор <a href="{% url 'progress:progress_exercise' exercise.id %}">Ввести прогресс упражнения</a><br />
            {% endfor %}
        {% endif %}
        <a href="{{ videos.before }}">вставка до</a><br />
        <a href="{{ videos.after }}">вставка после</a><br />
    {% endif%}

{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block content %}

    {% include 'blocks/header.html' %}
    {% if user.username %}
        {% if trainers %}
            {% for trainer in trainers %}
                {{ trainer.family_name }}, {{ trainer.name }} <a href='{% url "exercises:exercises" trainer.id %}'>Упражнения</a>, <a href='{% url "diets:diet_today" %}'>Диеты</a><br />
            {% endfor %}
        {% endif %}
    {% endif%}

{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block content %}

    <article>
        <h2 class="entry-title">
            Пожалуйста авторизуйтесь
        </h2>

        <form method="POST" action='.'>{% csrf_token %}
            <input type="username" value="" name="username" class="" placeholder="Учётная запись">
            <input type="password" value="" name="password" class="" placeholder="Пароль">
            <input type="submit" value="Войти" name="subscribe">
            <input type="hidden" name="next" value="{{ next }}"/>
            <div class="social">
                <a href="{% url 'social:begin' 'facebook' %}">fb</a>
                <a href="{% url 'social:begin' 'odnoklassniki-oauth2' %}">ok</a>
                <a href="{% url 'social:begin' 'vk-oauth2' %}">vk</a>
            </div>
        </form>

        <hr />
        <a href="/registration/">Зарегистрироваться</a><br />
        <a href="/password/reset/">Забыли пароль?</a>
        
    </article>


{% endblock %}

templates/profile.html
{% extends 'base.html' %}

{% block content %}

    <div>
        <a href="/">Главная</a>
    </div>
    <div class="profile">
        <div>
            <div>Мой профиль</div>
            <div>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <table>
                        <tbody>
                        <tr>
                            <td colspan="2">
                                аватар<br />
                                <img src="{% if user.avatar %}{{ user.avatar.url }}{% else %}/static/blocks/b-my-profile/example.png{% endif %}" height="150px"><br />
                                {{ form.avatar }}
                            </td>
                        </tr>
                        <tr>
                            <td>Эл. почта</td>
                            <td>{{ form.email }}</td>
                        </tr>
                        <tr>
                            <td>Фамилия</td>
                            <td>{{ form.last_name }}</td>
                        </tr>
                        <tr>
                            <td>Имя</td>
                            <td><input type="text" maxlength="255" name="first_name" value="{{ user.first_name }}" placeholder="при желании можно имя ввести с отчеством"></td>
                        </tr>
                        <tr>
                            <td>Пол</td>
                            <td>
                            <p><input list="sex" name="sex" value="{{ user.sex }}"></p>
                               <datalist id="sex">
                                <option value='m'>мужской</option>
                                <option value='f'>женский</option>
                               </datalist>
                           </td>
                        </tr>
                        <tr>
                            <td>Возраст</td>
                            <td>{{ form.age }}</td>
                        </tr>
                        <tr>
                            <td>Город</td>
                            <td>{{ form.city }}</td>
                        </tr>
                        <tr>
                            <td>Вес</td>
                            <td>{{ form.weight }}</td>
                        </tr>
                        <tr>
                            <td>Рост</td>
                            <td>{{ form.growth }}</td>
                        </tr>
                    </tbody></table>
                    <div>
                        <button type="submit">Сохранить</button>
                        <button type="reset">Сбросить</button>
                    </div>
                </form>
            </div>

        </div>


    </div>

{% endblock %}

templates/progress.html
{% extends 'base.html' %}

{% block content %}

    {% include 'blocks/header.html' %}
    Введите результаты выполнения упражнения: <br />
    <form method="post">
        {% csrf_token %}
        <table>
            <tr>
                <td>подходов</td>
                <td>{{form.sets}}</td>
            </tr>
            <tr>
                <td>повторов</td>
                <td>{{form.repetitions}}</td>
            </tr>
        </table>
        <div>
            <button type="submit">Сохранить</button>
            <button type="reset">Сбросить</button>
        </div>
    </form>

{% endblock %}

templates/registration-done.html
{% extends 'base.html' %}

{% block content %}

<article >
    <form  enctype="multipart/form-data" method="post">
        {% csrf_token %}
      <fieldset>
        <h2>
            Спасибо за регистрацию
        </h2>
        <p>В ближайшее время на указанный Вами почтовый ящик придёт письмо со ссылкой для активации.</p>
      </fieldset>
    </form>
</article>
{% endblock %}

templates/registration.html
{% extends 'base.html' %}

{% block content %}

<article>
    <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
      <fieldset>
        <h2>
            Регистрация
        </h2>

          <label for="input01">Имя</label>
          <div class="controls">
            <input type="text" name="first_name" id="input01" value="{{ form.first_name.value|default:''  }}">
          </div>
          {{ form.first_name.errors }}

          <label for="input01">Фамилия</label>
          <div class="controls">
            <input type="text" name="last_name" id="input01" value="{{ form.last_name.value|default:'' }}">
          </div>
          {{ form.last_name.errors }}

          <label for="input01">Email</label>
          <div class="controls">
            <div class="input-group">
              <input type="text" name="email" id="input01" value="{{ form.email.value|default:'' }}">
            </div>
          </div>
          {{ form.email.errors }}

          <label for="input01">Пароль</label>
          <div class="controls">
            <input type="password" name="password" id="input01" value="{{ form.password.value|default:'' }}">
          </div>
          {{ form.password.errors }}

        <br />
        
        <div>
          <button type="submit">Зарегистрироваться</button>
          {# <button>Отмена</button> #}
        </div>
        
      </fieldset>
    </form>
</article>
{% endblock %}

templates/reset_password-done.html
{% extends 'base.html' %}

{% block content %}

<article >
    <form  enctype="multipart/form-data" method="post">
        {% csrf_token %}
      <fieldset>
        <h2>
            Новый пароль выслан
        </h2>
        <p>В ближайшее время на указанный Вами почтовый ящик придёт письмо с новым паролем для входа в систему.</p>
      </fieldset>
    </form>
</article>
{% endblock %}

templates/reset_password.html
{% extends 'base.html' %}

{% block content %}

<article >
    <form  enctype="multipart/form-data" method="post">
        {% csrf_token %}
      <fieldset>
        <h2>
            Выслать новый пароль
        </h2>
        <p>Введите почтовый ящик который вы использовали для регистрации в системе.</p>
        <input type="text" maxlength="75" name="email" value="" placeholder="введите регистрационный email">
        <button type="submit">Выслать</button>
      </fieldset>
    </form>
</article>
{% endblock %}